analytics: {}
color:
  brandColors:
    - '#2b2223'
    - '#bab4a8'
    - '#864e2f'
    - '#ca8860'
    - '#e5e8a2'
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 1
  saturation: 0.839527
cta: {}
layout_spectrum: 0.50851
name: GOOD VIBRATIONS TATTOO STUDIO
opengraph: {}
purpose: []
typography_spectrum: 0.36011
