name: GOOD VIBRATIONS TATTOO STUDIO
favicon: null
layout_spectrum: 0.7560162518639117
typography_spectrum: 0.8136379267089069
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6562564980704337
  lightness: 0.8831154173240066
  saturation: 0.11344069126062095
  rhythmicContrast: 0.022763489745557308
purpose: []
